server:
  port: 8080
  # 上下文路径,默认为 / ,修改之后要把这个添加在访问路径上
  servlet:
    context-path: /wechat
spring:
  datasource:
    name: wechat
      # 采用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库的url，用户名，密码
    url: jdbc:mysql://127.0.0.1:3306/wechat?serverTimezone=GMT%2B8
    username: root
    password: 12306
    # 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 监控
    filter: stat
    # 连接池配置
    initial-size: 2 # 初始化链接
    max-idle: 10 # 最大空闲连接
    min-idle: 2 # 最小空闲连接
    max-active: 20 # 最大活跃连接
    # 等待超时h时间
    max-wait: 10000
    # 间隔多久进行一次检测，检测是否需要关闭空闲连接
    time-between-eviction-runs-millis: 10000
    min-evictable-time-millis: 100000
    validation-query: SELECT 'X'
    test-while-idle: true
    test-on-borrow: false
#  spring.datasource.druid.initial-size=
#  spring.datasource.druid.max-active=
#  spring.datasource.druid.min-idle=
#  spring.datasource.druid.max-wait=
#  spring.datasource.druid.pool-prepared-statements=
#  spring.datasource.druid.max-pool-prepared-statement-per-connection-size=
#  spring.datasource.druid.max-open-prepared-statements= #和上面的等价
#  spring.datasource.druid.validation-query=
#  spring.datasource.druid.validation-query-timeout=
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # mapUnderscoreToCamelCase 开启与数据库字段名称的驼峰匹配
  configuration:
    map-underscore-to-camel-case: true

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.87.140:22122
    - 192.168.87.140:22122